#!/usr/bin/env python3
"""
GIMP でIndexed Color変換済みの画像をEPD用C配列に変換するスクリプト
- GIMPで4色(white/yellow/red/black)に変換済みの画像を入力すること
- 4色: white=0x00, yellow=0x01, red=0x02, black=0x03
- 1ピクセル2bit、4ピクセル1byte (MSB first)
- 解像度: 960x640 (デフォルト、引数で変更可)

使い方:
  python img_to_epd.py <入力画像.png> [出力.h] [変数名] [幅] [高さ]
例:
  python img_to_epd.py photo_indexed.png epd_image.h gImage_1 960 640
"""

import sys
import numpy as np
from PIL import Image

# --- 電子ペーパーの色コード定義 ---
COLOR_MAP = {
    (255, 255, 255): 0x00,  # white
    (255, 255, 0  ): 0x01,  # yellow
    (255, 0,   0  ): 0x02,  # red
    (0,   0,   0  ): 0x03,  # black
}


def rgb_to_code(rgb):
    """RGB値をEPDコードに変換。完全一致しない場合は最近傍色を使用"""
    key = tuple(rgb)
    if key in COLOR_MAP:
        return COLOR_MAP[key]

    # 最近傍にフォールバック
    best_code, best_dist = 0x01, float('inf')
    for color_rgb, code in COLOR_MAP.items():
        dist = sum((a - b) ** 2 for a, b in zip(key, color_rgb))
        if dist < best_dist:
            best_dist, best_code = dist, code
    return best_code


def image_to_epd_array(input_path, width=960, height=640, output_var='gImage_1'):
    img = Image.open(input_path).convert('RGB')
    if img.size != (width, height):
        print(f"  画像サイズ {img.size} → ({width}, {height}) にリサイズします")
        img = img.resize((width, height), Image.NEAREST)
    pixels = np.array(img, dtype=np.uint8)

    print(f"[1/2] ピクセル変換中 ({width}x{height})...")
    codes = np.zeros((height, width), dtype=np.uint8)
    unknown_colors = set()
    for y in range(height):
        if y % 64 == 0:
            print(f"  {y}/{height} 行処理中...")
        for x in range(width):
            rgb = tuple(pixels[y, x])
            codes[y, x] = rgb_to_code(rgb)
            if rgb not in COLOR_MAP:
                unknown_colors.add(rgb)

    if unknown_colors:
        print(f"  ※ パレット外の色が {len(unknown_colors)} 種類ありました（最近傍で代替）:")
        for c in list(unknown_colors)[:5]:
            print(f"     RGB{c}")

    print(f"[2/2] パッキング & 出力中...")
    assert width % 4 == 0, "幅は4の倍数である必要があります"
    flat = codes.reshape(-1)
    num_bytes = len(flat) // 4
    packed = np.zeros(num_bytes, dtype=np.uint8)
    for i in range(num_bytes):
        packed[i] = (flat[i*4] << 6) | (flat[i*4+1] << 4) | (flat[i*4+2] << 2) | flat[i*4+3]

    array_size = len(packed)
    lines = [
        f'// Generated by img_to_epd.py',
        f'// Source: {input_path}',
        f'// Size: {width}x{height}, {array_size} bytes',
        f'#include <pgmspace.h>',
        f'',
        f'const unsigned char {output_var}[{array_size}] PROGMEM = {{',
    ]
    row_width = 16
    for i in range(0, array_size, row_width):
        chunk = packed[i:i+row_width]
        hex_str = ', '.join(f'0x{b:02X}' for b in chunk)
        comma = ',' if i + row_width < array_size else ''
        lines.append(f'  {hex_str}{comma}')
    lines += ['};', '']

    return '\n'.join(lines), array_size


def main():
    if len(sys.argv) < 2:
        print(__doc__)
        sys.exit(1)

    input_path  = sys.argv[1]
    output_path = sys.argv[2] if len(sys.argv) > 2 else 'epd_image.h'
    var_name    = sys.argv[3] if len(sys.argv) > 3 else 'gImage_1'
    width       = int(sys.argv[4]) if len(sys.argv) > 4 else 960
    height      = int(sys.argv[5]) if len(sys.argv) > 5 else 640

    c_code, size = image_to_epd_array(input_path, width, height, var_name)
    with open(output_path, 'w') as f:
        f.write(c_code)

    print(f"\n完了!")
    print(f"  C配列  : {output_path} ({size} bytes)")
    print(f"  配列名 : {var_name}[{size}]")


if __name__ == '__main__':
    main()